myproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^', include('polls.urls', namespace="polls")),
                  url(r'^', include('video.urls', namespace="video")),
                  url(r'^', include('talent.urls', namespace="talent")),
                  url(r'^', include('photo.urls', namespace="photo")),
              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'photo'



urlpatterns = [
    url(r'^create/$', views.pin_create, name='create'),

    url(r'^album/$', views.album, name='album'),

    url(r'^register/$', views.register, name='register'),

    url(r'^login_user/$', views.login_user, name='login_user'),

    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    url(r'^(?P<pk>[-\w]+)/$', views.show, name='show'),

]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^crew$', views.crew, name='crew'),
    # url(r'^(?P<crew_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^reels$', views.reels, name='reels'),

]

photo/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User




def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)



class Album(models.Model):
    user = models.ForeignKey(User, default=1)
    album_title = models.CharField(max_length=250)
    description = models.TextField()
    slug = models.SlugField(max_length=200, unique=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    editor = models.CharField(max_length=70)
    cover = models.FileField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)




    def __str__(self):
        return self.album_title

    def get_absolute_url(self):
        return reverse('show', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-created']


class Pin(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=200, unique=True)
    is_favorite = models.BooleanField(default=False)
    description = models.TextField()
    image = models.FileField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)



    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('show', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-timestamp','-created']

photo/forms.py
from django.contrib.auth.models import User
from .models import Album, Pin

from django import forms


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['editor', 'album_title', 'cover']


class PinForm(forms.ModelForm):
    class Meta:
        model = Pin
        fields = ['name', 
                'is_favorite',
                'image', 
                ]

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

photo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Album, Pin
from .forms import AlbumForm, PinForm, UserForm
from django.db.models import Q
from django.http import JsonResponse
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.views.generic import DetailView, ListView, CreateView


IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']



def pin_create(request):
    form = PinForm()
    context = {
        "form": form,
    }
    return render(request, "photo/pin_form.html", context)

def album(request):
    context = {
        'albums': Album.objects.all(),
    }
    return render(request, 'photo/album.html', context)


# def detail(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     return render(request, 'photo/photo_detail.html', {'album': album})


def show(request, pk):
    album = get_object_or_404(Album, pk=slug)
    template = 'photo/show.html'
    return render(request, template, {'album': album})




def Form(request):
    return render(request, 'photo/pin_form.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'photo/login_user.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'polls/index.html', {'albums': albums})
            else:
                return render(request, 'photo/login_user.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'photo/login_user.html', {'error_message': 'Invalid login'})
    return render(request, 'photo/login_user.html')

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'polls/index.html', {'albums': albums})
    context = {
        "form": form,
    }
    return render(request, 'photo/register.html', context)

def pin_update(request, id=None):
    instance = get_object_or_404(Pin, id=id)
    form = PinForm(request.POST or None, request.FILES or None, instance=instance)
    if form.if_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "<a href='#'> Item</a> Saved", extra_tags='html_safe')
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "name" : name,
        "instance": instance,
        "form" : form,
    }
    return render(request, "pin_form.html", context)

templates/photo/album.html
{% extends 'base.html' %}

{% block title %}INK | Albums{% endblock %}

{% block body %}
    <div class="container">
        <h3><i>Browse through our gallery of Albums</i></h3>
        {% for album in albums %}
            <div class="row">
                <div class="col-sm-4">
                    <a href="{% url 'photo:show' album.slug %}">
                        {% if album.cover %}
                            <img src="{{ album.cover.url }}" class="img-responsive" height="235" width="157">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h4>{{ album.album_title }}</h4>
                </div>
            </div>
        {% endfor %}
    </div>

    {% include "footer.html" %}


{% endblock %}


{#            <!-- Left Album Info -->#}
{#            <div class="col-sm-12 col-md-4">#}
{#                <div class="panel panel-default">#}
{#                    <div class="panel-body">#}
{#                        <a href="{% url 'photo:pin-detail' album.id %}">#}
{#                            {% if album.cover %}#}
{#                                <img src="{{ album.cover.url }}" class="img-responsive">#}
{#                            {% else %}#}
{#                                <h3>No image to display</h3>#}
{#                            {% endif %}#}
{#                        </a>#}
{#                        <small>{{ album.album_title }}</small>#}
{#                        <br>#}
{#                        <small><i>By: </i>{{ album.editor }}</small>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}

templates/photo/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}INK PRODUCTIONS{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/../../static/polls/../../static/polls/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'photo/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'polls:index' %}">INK PRODUCTIONS</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'photo:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'photo:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/photo/form.html
i am home

templates/photo/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

templates/photo/login_user.html
{% extends 'base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

<div class="container">
  <h3>Log In</h3>
  {% if error_message %}
  <p><strong>{{ error_message }}</strong></p>
  {% endif %}
  <form class="form-horizontal" role="form" action="{% url 'photo:login_user'%}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-2" for="id_username">
        Username:
      </label>
        <div class="col-sm-10">
          <input id="id_username" maxlength="30" name="username" type="text">
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="id_password">
        Password:
      </label>
      <div class="col-sm-10">
        <input id="id_password" maxlength="30" name="password" type="password">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-success">Submit</button>
      </div>
    </div>
  </form>
</div>
<p style="text-align:center;" >
  Don't have an account..? <a href="{% url 'photo:register' %}">Click here!</a> to register.
</p>
</div>


{% include "footer.html" %}

{% endblock %}

templates/photo/pin_form.html
{% extends 'base.html' %}

{% block title %}INK | Upload Photos{% endblock %}

{% load staticfiles %}

{% block content %}
    <h1>Form</h1>

    <div class="col-md-6 col-sm-offset-3">
        <h1>Form</h1>
        <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-default" value="Upload Photos" >
        </form>
    </div>

    {% include "footer.html" %}

{% endblock %}

templates/photo/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

  <!-- <div class="row"> -->
  <!-- <div class="col-sm-12 col-md-6"> -->
  <!-- <div class="panel panel-default"> -->
  <!-- <div class="panel-body"> -->
  <!-- <h3>Register for an Account</h3> -->
  <!-- {% if error_message %} -->
  <!-- <p><strong>{{ error_message }}</strong></p> -->
  <!-- {% endif %} -->
  <!-- <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data"> -->
  <!-- {% csrf_token %} -->
  <!-- {% include 'photo/form_template.html' %} -->
  <!-- <div class="form-group"> -->
  <!-- <div class="col-sm-offset-2 col-sm-10"> -->
  <!-- <button type="submit" class="btn btn-success">Submit</button> -->
  <!-- </div> -->
</div>
<!-- </form> -->
<!-- </div> -->
<!-- <div class="panel-footer"> -->
<!-- Already have an account? <a href="{% url 'photo:login_user' %}">Click here</a> to log in. -->
<!-- </div> -->
<!-- </div> -->
<!-- </div> -->
<!-- </div><!--  -->


<div class="container">
  <h3> Register for an Account </h3>
  {% if error_message %}

  <strong>{{ error_message }}</strong>
  {% endif %}

  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'photo/form_template.html' %}

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-success" > Submit</button>
      </div>
    </div>
  </form> 
</div>
<div>
  <p style="text-align:center;" >
    Already have an account? <a href="{% url 'photo:login_user' %}"> Click here </a> to log in.
  </p>
</div>

{% include "footer.html" %}

</div>


{% endblock %}

templates/photo/show.html
{% extends 'base.html' %}

{% block title %}INK | {{ album }}{% endblock %}

{% block albums_active %}active{% endblock %}

{% block body %}

    <h4 style="text-align: center">ALBUM: <i>{{ album.album_title }}</i></h4>

    <div class="container-fluid">
        {% for pin in album.pin_set.all %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="{{ pin.image.url }}" alt="...">
                </div>
            </div>
        {% endfor %}
    </div>

    {% include "footer.html" %}


{% endblock %}