myproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^', include('polls.urls', namespace="polls")),
                  url(r'^', include('video.urls', namespace="video")),
                  url(r'^', include('talent.urls', namespace="talent")),
                  url(r'^', include('photo.urls', namespace="photo")),
              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'photo'



urlpatterns = [
    url(r'^create/$', views.pin_create, name='create'),

    url(r'^album/$', views.album, name='album'),

    url(r'^register/$', views.register, name='register'),

    url(r'^login_user/$', views.login_user, name='login_user'),

    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    url(r'^(?P<pk>[-\w]+)/$', views.show, name='show'),

]

video/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'video'



urlpatterns = [
    # url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='video-detail'),
    url(r'^(?P<pk>\d+)/$', views.DetailView, name='video-detail'),
    url(r'^season/$', views.IndexView.as_view(), name='season'),
]

video/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.db import models
from embed_video.fields import EmbedVideoField


def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)





class Season(models.Model):
    season_name = models.CharField(max_length=250)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    editor = models.CharField(max_length=70)
    cover = models.ImageField(null=True, blank=True)
    slug = models.SlugField(unique=True)


    def __str__(self):
        return self.season_name

    def get_absolute_url(self):
        return reverse("video:video-detail", kwargs={"slug":self.slug})

    class Meta:
        verbose_name_plural = 'Seasons'
        ordering = ['season_name']

class Video(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True,)
    # link = models.URLField(max_length=500, blank=True, default='')
    link = EmbedVideoField()
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("video:video-detail", kwargs={"slug":self.slug})

    class Meta:
        verbose_name_plural = 'Videos'
        ordering = ['name']


# class Video(models.Model):
#     name = models.CharField(max_length=200,)
#     file_path = models.FileField(null=True, blank=True, upload_to='video')
#     season = models.ForeignKey(Season, on_delete=models.CASCADE)
#     description = models.TextField()
#     thumbnail = models.ImageField(null=True, blank=True)
#     created = models.DateTimeField(auto_now_add=True)
#     slug = models.SlugField(unique=True)
#
#
#     def __str__(self):
#         return self.name
#
#     def get_absolute_url(self):
#         return reverse("video:video-detail", kwargs={"slug":self.slug})
#
#     class Meta:
#         verbose_name_plural = 'Videos'
#         ordering = ['name', ]

def create_slug(instance, new_slug):
    slug = slugify(instance.name)
    if new_slug is not None:
        slug = new_slug
    qs = Video.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_video_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

        # pre_save.connect(pre_save_video_receiver, sender=Video)

video/views.py
from django.conf.urls import url
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView
from django.views import generic

from .models import Season, Video

VIDEO_FILE_TYPES = ['mp4']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']



class IndexView(generic.ListView):
    template_name ='video/season.html'

    def get_queryset(self):
        return Season.objects.all()



# class DetailView(generic.DetailView):
#     model = Season
#     template_name = 'video/video.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(DetailView, self).get_context_data(**kwargs)
#         context['video'] = Video.objects.get(id=pk)
#         return context

def DetailView(request, pk):
    video = get_object_or_404(Video, pk=pk)
    return render(request, 'video/video.html', {'video': video})

templates/video/season.html
{% extends 'base.html' %}

{% block title %}INK | Seasons {% endblock %}

{% load staticfiles %}


{% block body %}

    <div class="container">

        <div class="container-fluid" style="padding-bottom: 10px;">
            <h3 style="padding-left: 10%; position: relative;">Nairobi Diaries | Since 2015 </h3>
            <hr>


            <div class="container">
                <div class="row">
                    <div class="col-sm-4" style="padding-bottom: 10px;">
                        <img src="{% static "polls/../../static/images/first_slide.jpg" %}" alt="Nairobi Diaries | Videos" width="540" height="330">
                    </div>

                    <div class="col-md-offset-6 pull-md-9" style="padding-left: 10%; position: relative;">
                        <p>
                            Nairobi Diaries is a Kenyan reality television series that premiered on 14 December 2015 on K24.
                            <br>
                            The one-hour show stars entrepreneur and socialite Vera Sidika, fashion stylist Silvia Njoki,
                            <br>
                            musician and actress Ella Ciru, NGO ambassador and student Gertrude Murunga, architect Kiki Diang’a,
                            <br>
                            fitness instructor Marjolein Blokland and socialite and singer Pendo.
                        </p>

                        <br>

                        <h5> <strong style="padding-right: 40px; font-size: 15px;">Genres:</strong>      Drama | Comedy | Reality</h5>
                        <h5> <strong style="padding-right: 40px; font-size: 15px;">Duration:</strong>    45 mins</h5>
                        <h5> <strong style="padding-right: 15px; font-size: 15px;">Produced In:</strong> 2015-2016</h5>
                        <h5> <strong style="padding-right: 40px; font-size: 15px;">Starring:</strong>    Pendo,Judy,Dana</h5>
                    </div>
                </div>
            </div>



        </div>

        <br>
        <br>

        <div class="container-fluid">
            {% for season in object_list%}
                <button class="accordion">{{ season.season_name }}</button>
                <div class="panel">
                    {% for video in season.video_set.all %}
                        {% if video %}
                            <ul>
                                <a href="{% url 'video:video-detail' video.id %}">
                                    <button class="accordion">{{ video.name }}</button>
                                </a>
                            </ul>
                        {% else %}
                            <h3>Sorry..videos not uploaded yet</h3>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>

    </div>

    <br>

    <br>

    <script>
        var acc = document.getElementsByClassName("accordion");
        var i;

        for (i = 0; i < acc.length; i++) {
            acc[i].onclick = function(){
                this.classList.toggle("active");
                this.nextElementSibling.classList.toggle("show");
            }
        }

    </script>


    {% include "footer.html" %}

{% endblock %}

templates/video/video.html
{% extends 'base.html' %}
{% block title %} {{ season.name }} {% endblock %}
{% load staticfiles %}
{% load embed_video_tags %}

{% block body %}

    <div class="container" style="padding-bottom: 10%">
        <div style="text-align: center">
            <h3>{{ video.name }}</h3>
            <br>


            <iframe width="420" height="315" src="{{ video.link }} " frameborder="0" allowfullscreen></iframe>


            <br><br>
        </div>
    </div>

    {#ericcaleb1@gmail.com#}

    <script>
        var myVideo = document.getElementById("video1");

        function playPause() {
            if (myVideo.paused)
                myVideo.play();
            else
                myVideo.pause();
        }

        function makeBig() {
            myVideo.width = 756;
        }

        function makeSmall() {
            myVideo.width = 320;
        }

        function makeNormal() {
            myVideo.width = 520;
        }
    </script>

    {% include "footer.html" %}

{% endblock %}