myproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^', include('polls.urls', namespace="polls")),
                  url(r'^', include('video.urls', namespace="video")),
                  url(r'^', include('talent.urls', namespace="talent")),
                  url(r'^', include('photo.urls', namespace="photo")),
              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'photo'



urlpatterns = [
    url(r'^create/$', views.pin_create, name='create'),

    url(r'^album/$', views.album, name='album'),

    url(r'^register/$', views.register, name='register'),

    url(r'^login_user/$', views.login_user, name='login_user'),

    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    url(r'^(?P<pk>[-\w]+)/$', views.show, name='show'),

]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^crew$', views.crew, name='crew'),
    # url(r'^(?P<crew_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^reels$', views.reels, name='reels'),

]

talent/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'talent'



urlpatterns = [
    url(r'^talent/$', views.talent, name='talent'),
    url(r'^(?P<pk>\d+)/$', views.talent_detail, name='show'),
]

video/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'video'



urlpatterns = [
    # url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='video-detail'),
    url(r'^(?P<pk>\d+)/$', views.DetailView, name='video-detail'),
    url(r'^season/$', views.IndexView.as_view(), name='season'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}INK PRODUCTIONS{% endblock %}</title>
    <link rel="shortcut icon" href="{{ STATIC_URL }}ico/favicon.ico">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <link rel="stylesheet" href="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="{% static 'polls/js/main.js' %}"></script>
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
            <a href="{% url 'polls:index' %}">
                <img src="{% static "polls/../../static/images/ink_logo.png" %}" height="50" alt="Ink productions">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">

                {% if user.is_superuser %}
                    <li>
                        <a href="{% url 'admin:index' %}">Admin</a>
                    </li>

                {% endif %}

                <li>
                    <a href="{% url 'polls:index' %}">Home</a>
                </li>

                <li>
                    <a href="{% url 'polls:crew' %}">Crew</a>
                </li>


                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Nairobi Diaries
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <!-- <li><a href="#">XTRAS</a></li> -->
                        <li><a href="{% url 'photo:album' %}"> PHOTOS </a></li>
                        <li><a href="{% url 'video:season' %}">VIDEOS</a></li>
                        <li><a href="{% url 'talent:talent' %}">CAST</a></li>
                        <!-- <li><a href="#">FAVORITES</a></li> -->
                    </ul>
                </li>




                {# <a href="#">About Us</a>#} {# </li>#}
                <li>
                    <a href="{% url 'polls:contact' %}">Contact</a>
                </li>

                <!-- <li> -->
                <!--     <a href="{% url 'polls:reels' %}">Reels</a> -->
                <!-- </li> -->

                <li>
                    <a href="{% url 'photo:register' %}">Login|SignUp!</a>
                </li>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>



{% block body %} {% endblock %}

</body>

</html>

templates/footer.html
{% load staticfiles %}

<footer style="background-color: lightgrey;">

	<hr>

	<div class ="container">
		<div class ="row">

			<div class ="col-md-4">
				<p class= "conts" style="text-align: center;">

					INK PRODUCTIONS LTD.

					<br/>

					Email: inkproductionsltd@gmail.com

					<br/>

					Email: info@inkproductions.co.ke

					<br/>

					T air: +254 734755244  T saf: +254 722 568 460
					<br/>
					T saf: +254 721854821
					<br/>
					Nairobi, Kenya
				</p>
			</div>
			<div class ="col-md-3">
				<ul class="list-inline" style=" left: 40%;">
                    <img src="{% static "polls/../../static/images/facebook.png" %}" height="40" width="40" alt="facebook" >
                    <img src="{% static "polls/../../static/images/instagram.png" %}" height="40" width="40" alt="instagram" >
                    <img src="{% static "polls/../../static/images/twitter.png" %}" height="40" width="40" alt="twitter" >
				</ul>
			</div>

			<div class ="col-md-5">
				<div class="patners" style="text-align: center;">
					<h4>Our Patners</h4>
				</div>
				<ul class="list-inline" style=" left: 15%;">
                    <img src="{% static "polls/../../static/images/west_wood.jpg" %}" height="60" width="80" alt="west_wood" >
                    <img src="{% static "polls/../../static/images/4ina.jpg" %}" height="60" width="80" alt="4ina" >
                    <img src="{% static "polls/../../static/images/ebony.png" %}" height="60" width="80" alt="ebony" >
                    <img src="{% static "polls/../../static/images/club_life.jpg" %}" height="60" width="80" alt="club_life" >
                    <img src="{% static "polls/../../static/images/k24.jpg" %}" height="60" width="80" alt="k24" >
				</ul>
				<br>
				<ul class="list-inline" style="left: 40%;">
                    <img src="{% static "polls/../../static/images/unbeweavable.jpg" %}" height="60" width="60" alt="unbeweavable" >
                    <img src="{% static "polls/../../static/images/dent_group.png" %}" height="60" width="60" alt="dent_group" >
				</ul>
			</div>
		</div>
	</div>

	<div class = "mwisho" style="text-align: center;">
		<h4>Copyright &copy; 2017
            <br>
            <i>Revel Inc.</i> </h4>
		<h4>T +254 729-055-061 </h4>

	</div>

	<br>

</footer>